### ISSUE TITLE
Taille du champ VALEUR dans la table PREFERENCES_APPLICATION trop court

### ISSUE THREAD

**Issue by XavRsl** [EsupPortail/esup-mdw#1]
Bonjour !
Bon, il faut bien une première issue....
Comme indiqué dans le titre, la taille du champ VALEUR de la table PREFERENCES_APPLICATION étant limité à 200 caractère, celui-ci est trop court pour y stocker toute l'information dont on a besoin en particulier concernant l'entrée listeLoginsBloques : 

![champ_trop_court](https://cloud.githubusercontent.com/assets/1185840/18992289/b9e159ce-871d-11e6-92bc-5a6162f89f0b.png)

Au bout d'une vingtaine de numéros étudiant, le dernier est tronqué et les nouveaux étudiants bloqués ne le sont jamais.

J'ai conscience que l'UVSQ est probablement l'une des seules universités à utiliser cette option, mais elle est notre rempart contre la fraude (impayés de toutes sortes). 

Je ne sais pas si convertir ce champs en blob est la solution (sur 55 lignes ça ne devrait pas poser de problème de performance...).

Un simple ajout d'un fichier de migration pourrait faire l'affaire ?

``` sql
ALTER TABLE PREFERENCES_APPLICATION CHANGE VALEUR VALEUR BLOB;
```

Merci !

Xavier

**Comment by cdubois54** [comment]
Bonjour, 

Ce serait effectivement une solution rapide, sinon il faudrait que je prenne le temps de modifier l'application pour utiliser une table distincte pour stocker les listes de valeur. 

----- Le 30 Sep 16, à 15:08, XavRsl notifications@github.com a écrit : 

> Bonjour !
> Bon, il faut bien une première issue....
> Comme indiqué dans le titre, la taille du champ VALEUR de la table
> PREFERENCE_APPLICATION étant limité à 200 caractère, celui-ci est trop court
> pour y stocker toute l'information dont on a besoin en particulier concernant
> l'entrée listeLoginsBloques :
> 
> Au bout d'une vingtaine de numéros étudiant, le dernier est tronqué et les
> nouveaux étudiants bloqués ne le sont jamais.
> 
> J'ai conscience que l'UVSQ est probablement l'une des seules universités à
> utiliser cette option, mais elle est notre rempart contre la fraude (impayés de
> toutes sortes).
> 
> Je ne sais pas si convertir ce champs en blob est la solution (sur 55 lignes ça
> ne devrait pas poser de problème de performance...).
> 
> Un simple ajout d'un fichier de migration pourrait faire l'affaire ?
> ALTER TABLE PREFERENCE_APPLICATION CHANGE VALEUR VALEUR BLOB;
> 
> Merci !
> 
> Xavier
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub , or mute the thread .

## 

---

Charlie Dubois 
Direction du Numérique - SIED 
Université de Lorraine 
24-30 rue Lionnois 
54000 NANCY 
Tél : 03.83.68.53.77

**Comment by XavRsl** [comment]
Je vais tenter de changer ça chez nous et j'essaie de te faire un retour pour te dire si tout continue de fonctionner correctement.

Xavier

**Comment by cdubois54** [comment]
Faites peut être un export de la base avant. 
Je suis en train de regarder pour utiliser une table séparée sinon. Si vous pouvez attendre quelques jours 

----- Le 3 Oct 16, à 9:41, XavRsl notifications@github.com a écrit : 

> Je vais tenter de changer ça chez nous et j'essaie de te faire un retour pour te
> dire si tout continue de fonctionner correctement.
> 
> Xavier
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub , or mute the thread .

## 

---

Charlie Dubois 
Direction du Numérique - SIED 
Université de Lorraine 
24-30 rue Lionnois 
54000 NANCY 
Tél : 03.83.68.53.77

**Comment by XavRsl** [comment]
On peut attendre quelques jours ! Et ne t'inquiètes pas, on ne fera pas ça sans backup. Si tu penses qu'une base séparée est mieux, à toi de voir. Mais il faut aussi considérer le fait que d'autres valeurs de cette table peuvent aussi potentiellement faire plus de 200 caractères. Je pense en particulier à certScolProfilDesactive, certScolStatutDesactive, certScolTypDiplomeDesactive et codesEtapeAffichageRang. En gros, tous les champs qui doivent accueillir une liste.

**Comment by cdubois54** [comment]
Oui, oui j'y pensais. Je pense en profiter pour moderniser la vue admin. 

----- Le 3 Oct 16, à 10:08, XavRsl notifications@github.com a écrit : 

> On peut attendre quelques jours ! Et ne t'inquiètes pas, on ne fera pas ça sans
> backup. Si tu penses qu'une base séparée est mieux, à toi de voir. Mais il faut
> aussi considérer le fait que d'autres valeurs de cette table peuvent aussi
> potentiellement faire plus de 200 caractères. Je pense en particulier à
> certScolProfilDesactive, certScolStatutDesactive, certScolTypDiplomeDesactive
> et codesEtapeAffichageRang. En gros, tous les champs qui doivent accueillir une
> liste.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub , or mute the thread .

## 

---

Charlie Dubois 
Direction du Numérique - SIED 
Université de Lorraine 
24-30 rue Lionnois 
54000 NANCY 
Tél : 03.83.68.53.77

**Comment by cdubois54** [comment]
Bonjour, 

Je viens de commiter sur la branche master. 
Avez-vous la possibilité de tester cette version depuis le source présent sur github avant que je la distribue ou dois-je vous fournir un war? 

Charlie 

----- Le 3 Oct 16, à 10:08, XavRsl notifications@github.com a écrit : 

> On peut attendre quelques jours ! Et ne t'inquiètes pas, on ne fera pas ça sans
> backup. Si tu penses qu'une base séparée est mieux, à toi de voir. Mais il faut
> aussi considérer le fait que d'autres valeurs de cette table peuvent aussi
> potentiellement faire plus de 200 caractères. Je pense en particulier à
> certScolProfilDesactive, certScolStatutDesactive, certScolTypDiplomeDesactive
> et codesEtapeAffichageRang. En gros, tous les champs qui doivent accueillir une
> liste.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub , or mute the thread .

## 

---

Charlie Dubois 
Direction du Numérique - SIED 
Université de Lorraine 
24-30 rue Lionnois 
54000 NANCY 
Tél : 03.83.68.53.77

**Comment by XavRsl** [comment]
Je n'ai pas de serveur de test pour cette appli.... Je veux bien un war si ça ne te prends pas trop de temps. Penses-tu que je puisse le déployer directement sur la prod ?

**Comment by cdubois54** [comment]
Oui, à condition de faire un export de la table 'preferences_application' avant et de garder la version précédente de l'application prête au cas où (on ne sait jamais).
Quand ce sera validé, je mettrais à dispo pour tout le monde.

**Comment by XavRsl** [comment]
Désolé Charlie, on ne pourra pas tester tout de suite. Je vais devoir créer un environnement de test (avec mon collègue Belkacem) car on est encore en version 1.1.8, nos serviceWeb Apogee étant encore en 470lbj. On va donc passer directement à la version que tu viens de me livrer mais ça va prendre un peu plus de temps... Je te tiens au courant.

**Comment by cdubois54** [comment]
Ok pas de problème. 
Sinon, vous deviez pouvoir juste remplacer le jar des WS (dans le répertoire lib) par celui de la version précédente , ça devrait fonctionner.

**Comment by XavRsl** [comment]
Hello,
On a pu tester la nouvelle organisation. Nous avons donc bien à présent une liste d'entrées dans la table PREFERENCES_APPLICATION_VALEURS avec PREF_ID 'listeLoginsBloques' et VALEUR à l'identifiant (numéro d'étudiant) de l'étudiant que l'on veut bloquer. Il semble néanmoins que les étudiants en question ne soient pas bloqués dans l'application... J'ai fait le test avec 5 comptes différents. Aurais-tu une idée d'ou pourrait venir le problème ?

Merci.

Xavier

**Comment by cdubois54** [comment]
Effectivement j'ai laissé trainer un bug.
Je te transmets la correction dès que j'ai packagé ça

**Comment by XavRsl** [comment]
Super ! Merci beaucoup !

**Comment by cdubois54** [comment]
Désolé pour le bug, voici le war corrigé

**Comment by XavRsl** [comment]
OK, parfait. Tout à l'air de fonctionner à présent.

Merci beaucoup pour le travail que tu fournis !

Xavier

**Comment by cdubois54** [comment]
De rien. Merci d'avoir tester. Ce sera inclut dans la prochaine livraison du coup :)
