### ISSUE TITLE
Résultat manquante pour les étapes en crédit

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#10]
Bonjour,
Dans le cas d'une étape en crédit, le résultat ne s'affiche pas à l'écran.
Après vérification dans le code et dans le retour de la méthode recupererContratPedagogiqueResultatVdiVet_v2, il apparait que le champs annee de l'étape en crédit est null. De fait, lors de l'ajout à la liste, cette itération n'est pas ajoutée aux contrats à afficher (cpdtoAl).
Pour éviter ce problème, il faudrait que le test se base sur l'année (codAnu) de l'étape et pas celle du contrat.
Cordialement,
Yoann Lecuyer

**Comment by cdubois54** [comment]
Bonjour,

pourriez vous m'envoyer le SOAP en question par mail svp?
Si "le champs annee de l'étape en crédit est null" on ne peut pas se baser dessus justement.
Après si l'année du contrat est null et pas celle de l'étape, il y a peut etre un soucis au niveau du WS.

Cdlt

**Comment by cdubois54** [comment]
Merci pour l'envoi de l'enveloppe SOAP.

Je viens de créer une DA auprès de l'AMUE (N°133470) car il est anormal que l'année de soit pas renseignée par le WebService. En effet, elle est indiquée comme obligatoire dans le contrat de service (contrat_service_pedagogique.pdf)

**Comment by cdubois54** [comment]
Bonjour,

pour information, la demande d'assistance n°133470 va être présentée pour arbitrage en vue d'une correction ou d'une modification de produit.

**Comment by gmartel** [comment]
Bonjour Charlie,

J'ai également fait une DA à l'AMUE (N°136381) pour appuyer la tienne.
Voici la réponse que j'ai obtenu :

> Après échange avec notre prestataire en charge de la maintenance d'Apogée, il ne s'agirait pas d'une anomalie mais plutôt d'une évolution du connecteur.
> Même si l'année au diplôme est indiquée comme obligatoire sur le contrat de service, il s'avère que dans le cas des étapes en dette ou en crédits (pour lesquelles il n'y a pas d'IA), toutes les données du premier niveau relatives au diplôme sont remontées vides, dont l'année car nous ne pouvons pas déterminer au titre de quel diplôme l'étudiant est inscrit (cf. p16 §.2.2.1.5 Règles de gestion). En revanche, si vous renseignez l'année en paramètre d'entrée du connecteur, ce problème ne se produit pas (uniquement si valeur à 'toutes').
> 
> Pour répondre à ce problème, il faudrait toujours restituer l'année du diplôme même pour une VET en dette/crédit. Comme il s'agit d'une évolution, je ne saurai vous dire si elle pourra être prise en compte et dans quel délai.
> En attendant une éventuelle modification du connecteur, et comme indiqué dans la fiche n°133470, vous pouvez utiliser à la place l'année au niveau de l'étape (codAnu).

Cdlt,
Guillaume

**Comment by cdubois54** [comment]
Si je comprends bien, on n'a pas l'année du contrat sur les étapes en dette/crédit car on ne ne peut pas déterminer le diplôme associé mais en tant que demande d'évolution, c'est finalement possible?
Bon... 
Je vais modifier pour la prochaine version de mdw : test sur l'année du premier item de la liste "etapes" si l'année du contrat est null. 
A priori, ça corrigerait votre problème je pense?

**Comment by yoannlecuyer** [comment]
Bonjour Charlie,
De notre coté, on a investigué un peu plus et on a trouvé une solution.
Elle consiste, dans les méthodes recupererNotesEtResultats et recupererNotesEtResultatsEnseignant à renseigner l'année lors de la récupération de l'année en cours, basée sur Apogee-extraction.
En faisant cela, le webservice renseigne le champs annee  de l'étape, contrairement à l'appel fait en mettant "toutes" pour le champs année.

**Comment by cdubois54** [comment]
Bonjour,

en fait j'ai déjà fait la modification dont je parlais dans mon précédent message. Si vous voulez tester, c'est dans la branche master. Mais il faut surtout que je fasse une nouvelle release.
Après , l'appel au WS n'étant pas forcément hyper performant, cela pourrait être problématique de multiplier les appels. 
Mais c'est très intéressant pour éventuellement compléter la demande à l'AMUE. En effet, si le comportement n'est pas le même avec l'année en paramètre, on ne peut pas considérer que le comportement précédent est normal pour le coup...

**Comment by cdubois54** [comment]
edit : la DA 133470 est "en maintenance", il n'est plus possible de la compléter.

**Comment by cdubois54** [comment]
La modification est disponible dans la version 1.3.0
