### ISSUE TITLE
Affichage éléments capitalisés dans l'inscription pédagogique

### ISSUE THREAD

**Issue by gmartel** [EsupPortail/esup-mdw#11]
Bonjour Charlie,
Nous constatons des anomalies d'affichage des éléments capitalisés dans la consultation des inscriptions pédagogiques dans MDW.
Il est difficile de repérer les éléments capitalisés. On ne les distingue que s'ils portent des ECTS mais dans ce cas, au lieu d'afficher 3/3 pour un élément capitalisé portant 3 ECTS par exemple, il est affiché 0/3. Cette erreur ne se produit pas dans la partie Notes & Résultats.
Est-il possible de mettre une signalétique plus claire pour les éléments capitalisés dans l'inscription pédagogique et est-il possible de corriger l'affichage des ECTS pour ces éléments ?
Merci d'avance.
Guillaume

**Comment by cdubois54** [comment]
Bonjour,

si je comprends bien, on a donc à la fois un bug et une demande d'évolution?

Le bug : Affichage erroné des ECTS dans la popup du détail de l'inscription pédagogique affichée depuis la vue "Inscriptions"

L'évo : Rendre plus visibles les éléments qui ont des des crédits ECTS dans la popup du détail de l'inscription pédagogique affichée depuis la vue "Inscriptions"

C'est bien cela?

**Comment by gmartel** [comment]
Bonjour Charlie,
C'est effectivement cela.
Guillaume

**Comment by cdubois54** [comment]
Bonjour,

Le bug :  Je n'arrive pas à le reproduire. Peut être que cela vient du fait que, sur la vue du détail des notes on utilise l'extraction Apogée si elle est paramétrée pour. Dans la vue détail des Inscriptions on n'utilise JAMAIS les extractions. Cela avait été demandé par des universités, car elles avait des popup détail Inscriptions vide. Cela peut il être la cause ? A noter que pour afficher ces crédits MDW appelle la fonction CREDIT_ACQUIS_ELP du package PKB_CRD car ils ne sont pas retournés par le WebService. Une DA (121601) pour retourner l'info dans le WS est en attente de développement depuis bientôt un an et demi... Je peux néanmoins rajouter un paramètre affECTSEtudiant spécifique à la vue Inscriptions. De cette manière on pourrait les voir en vue Notes et les masquer en vue Inscriptions?

L'évo : je peux rajouter un style css "ects-label" sur les label contenant les libellés web des ELP dont la colonne crédit ECTS n'est pas vide. Après libre à vous de jouer avec le css personnalisé de mdw pour modifier l'affichage du libellé de l'ELP?

**Comment by gmartel** [comment]
Bonjour Charlie,

Nous utilisons effectivement les extractions à Rennes 1. C'est peut-être lié donc.

Pour l'évolution, je pensais plus à quelque du type de ce qui se fait dans la consultation du contrat pédagogique de l'application ipweb de l'AMUE qui contient une colonne "Note / Rés. Réutilisé". Bref, quelque chose qui permette à l'étudiant de voir que l'élément est bien capitalisé.

**Comment by cdubois54** [comment]
Je viens de trouver et résoudre un bug lié aux crédits ECTS qui étaient erronés. 
Mais l'erreur était présente dans les 2 vues, Notes & Résultats et Inscription. En tout cas sans utiliser les extractions...
Peut être que cela résoudra aussi votre soucis pour le coup.
Ce sera du coup corrigé dans la prochaine version. 

Pour l'évolution : Un peu l'équivalent du de la colonne "Résultat" qui affiche 'V' dans la partie Notes et Résultats en fait? Par exemple une colonne "Acquis" qui afficherait une sorte de coche en V ?

**Comment by cdubois54** [comment]
La correction est disponible dans la version 1.3.0

**Comment by yoannlecuyer** [comment]
Bonjour Charlie,
Après avoir fait quelques tests, il semblerait que le correctif ait eu comme effet de bord de mettre à 0 les crédits ECTS de l'année en cours. Les crédits pour les années capitalisées sont corrects mais rien pour l'année en cours.
Il faudrait que les crédits soient correctement affichés.
Merci d'avance.
Yoann

**Comment by cdubois54** [comment]
Bonjour Yoann,

je viens de revérifier et je n'ai, à priori, pas ce soucis.
J'ai sous les yeux un étudiant avec les 2 possibilités.

1 - Des crédits obtenus lors de l'année en cours : Parfois valués , parfois à 0 suivant le résultat obtenus (et peut être l'état de délibération j'imagine).
On les distingue car il n'y a pas d'année affichée à gauche du code de l'ELP (dans la colonne "Année" qui n'est affichée que si nécessaire)
Dans ce cas, pour récupérer les crédits obtenus, MDW appelle la fonction APOGEE.PKB_CRD.CREDIT_ACQUIS_ELP en indiquant l'année affichée affichée dans l'entête du tableau.

2 - Des crédits capitalisés lors de l'année précédente. 
On les distingue car il y a une année affichée à gauche du code de l'ELP (dans la colonne "Année")
Dans ce cas MDW appelle la fonction APOGEE.PKB_CRD.CREDIT_ACQUIS_ELP en indiquant l'année affichée dans la colonne "Année".

Tu constates des ELP où aucune année n'est pas renseignée dans la colonne "Année" et où le crédit indiqué est 0 alors qu'il devrait y avoir une valeur, c'est ça?

A noter que la prochaine livraison des WebServices  520laa retournera directement les crédit obtenus lors de l'appel au WebServices. Plus besoin oour MDW d'appeler APOGEE.PKB_CRD.CREDIT_ACQUIS_ELP. Ca devrait, espérons-le régler tous les problèmes.

**Comment by yoannlecuyer** [comment]
Bonjour Charlie,
Après vérification, il s'avère que je testais avec les WS de prod mais connecté sur la base de test.
Ce décalage faisait que l'appel à APOGEE.PKB_CRD.CREDIT_ACQUIS_ELP était erroné.
En changeant ce point, je valide donc que les crédits sont affichés correctement.
Merci à toi.
Yoann
