### ISSUE TITLE
Problème sur l'affichage du champs Etudiant Salarié

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#12]
Bonjour,
Dans l'écran des informations annuelles de l'étudiant, on a remarqué que l'information du champs Etudiant Salarié était la plupart du temps erronée. 
En effet, alors que la catégorie socio-professionnelle de l'étudiant est à 84 - élève, le champs Etudiant Salarié indique vrai.
En regardant dans le code de la méthode recupererEtatCivil, il s'avère qu'on met à vrai si c'est une autre valeur que 81, 82, 99 et A mais qu'il manque 84.
Merci de patcher la méthode.
Cordialement,
Yoann

**Comment by cdubois54** [comment]
Bonjour,

merci pour ce retour. Je viens de commiter la correction, la méthode sera donc valide dans la prochaine livraison.
Bonne journée

**Comment by cdubois54** [comment]
La modification est disponible dans la version 1.3.0
