### ISSUE TITLE
Problème d'affichage de relevé de notes

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#13]
Bonjour,
Pour nos relevé de notes issus d'une maquette d'extraction, nous rencontrons plusieurs problèmes : 
- l'ordre des éléments de la maquette n'est pas respecté, cet ordre n'étant pas présent dans le webservice recupererContratPedagogiqueResultatElpEpr
- la surcharge du libellé de l'ELP possible dans l'édition de maquette n'est pas affichée

La solution qui nous conviendrait serait, pour les relevés de notes de l'année courante, si on fait une extraction, se baser non pas sur le webservice mais sur une requête définie dans apogeeRequest
Merci d'avance.
Yoann

**Comment by cdubois54** [comment]
Bonjour,

le WebService Apogée avec le fonctionnement "extraction" ne retourne pas les données attendues ou vous souhaitez un comportement différent de celui prévu par le WebService?

Dans le premier cas, une DA parait normalement la meilleure solution mais peut être avez vous déjà essayé.

Dans le 2em cas, depuis la version 1.2.3 du 12/10/2018 il est possible de développer sa propre interface pour l'implémentation des résultats (paramètre resultat.implementation dans context.xml). Cela permet de surcharger le comportement actuel de MDW pour la récupération des notes et résultats en développant sa propre classe java (cf [Personnalisation ](https://www.esup-portail.org/wiki/display/PROJMONDOSSIERWEB/3.+Personnalisation)dans le wiki). Cela avait justement été demandé par certaines universités que ne s'en sortait pas avec les extractions et qui n'arrivaient pas à obtenir le comportement souhaité. 

Côté UL nous n'utilisons pas les extractions nous ne pouvons donc pas implémenter ni tester ces configurations. Les besoins concernant les extractions semblant vraiment différer en fonction des universités,  il aurait été de toute façon difficile de développer une solution "manuelle" (avec requêtes SQL) qui convienne à tout le monde. L'utilisation des Web Services Apogée devant normalement répondre à la majorité des cas.

Charlie
