### ISSUE TITLE
NullPointer sur la récupération de notes d'une épreuve

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#14]
Dans la méthode setNotesElpEpr de ResultatController, on a intercepté un NullPointer dans le cas d'une épreuve n'ayant pas d'état de délibération.
Le NullPointer intervient dans le cas d'un relevé de notes Apogée-extraction dans cette partie de code : 
```
if(!recuperationNote){
	//On n'a pas renseigné de liste de type épreuve à afficher ou celui ci n'était pas dans la liste
	if (codsession < 2) {
		if(temoinEtatDelib.contains(repdto[k].getEtatDelib().getCodEtaAvc()) || elpEtatDelibS1OK || TemCtlValCadEpr.equals(configController.getTemoinCtlValCadEpr()))
			recuperationNote = true;
	}else{
		if(temoinEtatDelib.contains(repdto[k].getEtatDelib().getCodEtaAvc()) || elpEtatDelibS2OK || TemCtlValCadEpr.equals(configController.getTemoinCtlValCadEpr()))
			recuperationNote = true;
	}
}
```
Le NullPointer se fait sur repdto[k].getEtatDelib() qui est null dans le SOAP.
Comme solution, j'ai ajouté un test de nullité du champs mais dans le cas d'une extraction, il faudrait forcer recuperationNote à true.

**Comment by cdubois54** [comment]
je regarderai ça.
On est certain de vouloir afficher les notes quand l'état est null lors d'une extraction?

**Comment by yoannlecuyer** [comment]
Selon Guillaume, lors d'une extraction, on ne tient pas compte de l'état de délibération.

**Comment by cdubois54** [comment]
D'accord, c'est noté.

**Comment by cdubois54** [comment]
La modification est disponible dans la version 1.3.0
