### ISSUE TITLE
Augmentation logs LDAP

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-mdw#15]
Bonjour,

Depuis hier nous rencontrons, en soirée, des soucis d'authentification liés au remplissage de la partition de logs de notre annuaire openldap. 

En y regardant de plus près, le remplissage est dû à un nombre excessif de requêtes issues de nos serveurs hébergeant l'application Esup-MDW.

_[ cat openldap.log | grep '172.16.2.24[8|9]' | wc -l
781690_

Soit presque 800000 connections en 12h.

un exemple de log :

_Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 fd=266 ACCEPT from IP=172.16.2.249:60781 (IP=172.30.18.66:389)
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=0 BIND dn="cn=appliweb_all_ro,ou=System,dc=ldap,dc=uhb,dc=fr" method=128
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=0 BIND dn="cn=appliweb_all_ro,ou=System,dc=ldap,dc=uhb,dc=fr" mech=SIMPLE ssf=0
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=0 RESULT tag=97 err=0 text=
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21804675)"
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=1 SRCH attr=uid mail edupersonprimaryaffiliation supannEtuId objectClass javaSerializedData javaClassName javaFactory javaCodeBase javaReferenceAddress javaClassNames javaRemoteLocation
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=2 UNBIND
Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 fd=266 closed_

Par conséquent, on aimerait savoir à quel moment l'application Esup-MDW interroge LDAP (sachant que nous n'utilisons pas les vues "enseignants") et surtout si vous avez des pistes pour y remédier ?

Merci d'avance.

Cdt.

**Comment by devwald** [comment]
Bonjour,

Je complète avec l'analyse de mon collègue qui gère le LDAP : 

l'application effectue une requête vers LDAP à chaque F5 ce qui serait étrange puisque la personne est déjà authentifiée sur le service. Il s'agit de requête permettant uniquement d'obtenir le supannEtuId, le mail ou l'affiliation :

    Feb 27 10:59:52 v-hyperion-1 slapd[22713]: conn=374855 op=1 SRCH attr=uid mail edupersonprimaryaffiliation supannEtuId objectClass javaSerializedData javaClassName javaFactory javaCodeBase javaReferenceAddress javaClassNames javaRemoteLocation

Ces données une fois obtenus devraient être mise en session utilisateur et ne devrait plus être demandées pour la session en cours.

Dans tous les cas, il y a clairement un dysfonctionnement de l'application :

    Feb 27 08:09:06 v-hyperion-1 slapd[22713]: conn=2548 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21709901)"
    Feb 27 08:09:06 v-hyperion-1 slapd[22713]: conn=2555 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21709901)"
    Feb 27 08:09:06 v-hyperion-1 slapd[22713]: conn=2558 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21709901)"
    Feb 27 08:09:06 v-hyperion-1 slapd[22713]: conn=2560 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21709901)" 

Y'a 4 SRCH identique dans la même seconde pour le même étudiant. Et ca fait ca pour tous visiblement) ou pire :

    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980591 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980592 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980593 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980594 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980595 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980596 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980597 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980598 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980599 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980600 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980601 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980602 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980603 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"
    Feb 28 04:09:25 v-hyperion-1 slapd[22713]: conn=1980604 op=1 SRCH base="ou=people,dc=ldap,dc=uhb,dc=fr" scope=2 deref=3 filter="(uid=21505534)"

Merci d'avance pour votre aide.

Cdt.

**Comment by cdubois54** [comment]
Bonjour,

pour information, je regarde le problème.

**Comment by cdubois54** [comment]
Bonjour,

une solution a été trouvée. Nous allons la tester dans notre environnement et elle sera livrée dans la prochaine version.

Cdt

**Comment by devwald** [comment]
Merci beaucoup.
Cdt.

**Comment by cdubois54** [comment]
Pour information, suite à la modification, nous sommes actuellement bloqué sur un problème (qui survient en prod) que nous n'arrivons pas à reproduire.

**Comment by cdubois54** [comment]
La correction est disponible dans la version 1.3.0

**Comment by richard333444** [comment]
> La correction est disponible dans la version 1.3.0
