### ISSUE TITLE
Problème sur la vue mobile en lien avec les extractions

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#16]
Bonjour,
Le sujet avait déjà été abordé par mail mais je n'avais pas fait d'issue à ce sujet.
Pour résumer la situation, dans la vue mobile, l'affichage du tableau provoque une erreur (trace en fichier attaché) lorsqu'avec les extractions, il n'y a pas de niveau 1 dans l'arborescence des éléments à afficher.
Il faudrait voir quelle solution constitue malgré tout le tableau car au final nos étudiants ne peuvent pas afficher en vue mobile leurs résultats en cours de publication.
Cordialement,
Yoann Lecuyer

[logErreurVueMobile.txt](https://github.com/EsupPortail/esup-mdw/files/3165384/logErreurVueMobile.txt)

**Comment by cdubois54** [comment]
Bonjour,

la vue mobile est plus "optimisée" que la vue Desktop afin de rendre la lisibilité moins compliquée sur un petit écran.
Elle se base donc sur une arborescence d'ELP afin de proposer :
- un code couleur par "branche"
- de déplier/replier certains niveaux
- des indicateurs colorés de niveau (remplaçant l'indentation de la vue bureau) sur chaque ELP pour améliorer la lisibilité de l'arborescence

Si la liste d'ELP à afficher n'a plus une arborescence valide cela empêche le fonctionnement des éléments décrits ci-dessus .

Je propose la solution suivante : Afficher la liste "basiquement" (sans code couleur, sans indicateurs etc.) à partir du moment où on détecte un soucis dans l'arborescence. 
On part là dessus?

**Comment by yoannlecuyer** [comment]
Bonjour Charlie,
Ta proposition me parait convenable sachant que souvent, les maquettes posant problème affichent peu d'éléments et donc en vue mobile, le contenu sera facile à lire.
Merci à toi.
Yoann

**Comment by cdubois54** [comment]
J'ai fais une modification de code qui sera disponible dans la prochaine version.
Le est sur la branche master du git. Sinon je peux envoyer un lien pour télécharger le war afin de tester et valider?

**Comment by yoannlecuyer** [comment]
je veux bien le lien vers le war, ce sera plus pratique pour moi.

**Comment by cdubois54** [comment]
Un lien a été envoyé par mail.
