### ISSUE TITLE
Erreur sur l'année en cours dans utilisationExtractionApogee

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#17]
Nous avons constaté que l'année en cours dans utilisationExtractionApogee n'était pas correcte.
En effet, lorsqu'on fait des extractions, notamment au moment du changement de l'année universitaire, l'année en cours peut être différente que celle des résultats.
Ainsi, dans le cas en fin d'année, on cherchera des extractions pour 2019 alors que c'est la 2018 la bonne.

Il faudrait donc faire une méthode similaire à getAnneeUnivEnCours  qui serait getAnneeResultatEnCours qui ferait appel à la requête suivante **select max(cod_anu) from annee_uni where eta_anu_res = 'O'**.

**Comment by cdubois54** [comment]
On parle ici de la vue Notes et Résultats (aux Diplômes et VET) ?

Incrémenter le paramètre notesNombreAnneesExtractionApogee ne résout pas le soucis?

**Comment by cdubois54** [comment]
Sans réponse, je clos la demande.
