### ISSUE TITLE
Problème avec les adresses étrangères

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#18]
Nous avons un problème lorsque les étudiants veulent modifier leur adresse (fixe dans le problème qui nous a été remonté) en saisissant une adresse à l'étranger.
En effet, lorsqu'on saisit un pays autre que France, le champs Ville se limite à 5 caractères, comme si c'était le champs Code postal.
Il faudrait pouvoir saisir correctement la ville.

**Comment by cdubois54** [comment]
En effet, la contrainte sur la taille des champs correspondant à la ville pour une adresse à l'étranger était erronée.
Ce bug a été corrigé sur la branche master et sera donc disponible lors de la prochaine version qui sera dispo dès que le dépôt sur SourceSup sera à nouveau opérationnel.
Merci pour la remontée de ce bug.

**Comment by yoannlecuyer** [comment]
Merci pour la modification. J'ai appliqué le patch et tout est ok.
