### ISSUE TITLE
Problème d'affichage des notes de sessions 2

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#19]
Bonjour,
Sur l'affichage des notes d'une étape, on a constaté que la note obtenue en session 2 pour l'étape s'affiche dans la colonne de la session 1.
Même si sur la page principale, on lit bien que c'est une note obtenue en session 2, le doute est présent et on a plusieurs remontées d'étudiants sur ce problème.
Il faudrait que la note de session 2 de l'étape apparaisse bien dans la bonne colonne.
Cordialement,
Yoann

**Comment by cdubois54** [comment]
Bonjour,
Pourriez vous préciser ou joindre une copie d'écran svp?
Ci dessous un exemple (ne posant pas problème) où les notes de l'écran "Notes & Résultats" sont correctement reprises sur le "Détail des notes" :

![notesEtape](https://user-images.githubusercontent.com/18556108/61048182-722c8480-a3e1-11e9-900f-aefdc890a28f.png)

**Comment by yoannlecuyer** [comment]
Bonjour,
Le problème d'affichage se fait sur le détail des notes. Cf mon impression d'écran, la note 8.864 devrait apparaitre en session 2. Je pense que le problème vient de l'extraction qui ne remonte pas la note d'étape pour la session 1 mais dans la réponse SOAP, c'est bien mis Session 2.

![image](https://user-images.githubusercontent.com/2776544/61048633-aa809280-a3e2-11e9-8bb5-2c4ca0825494.png)

**Comment by cdubois54** [comment]
Effectivement, lors de la reprise de l'étape (affichée dans "Notes & Résultats") pour l'ajouter en tête de la liste des ELP, on regarde le nombre de résultats de l'étape. Si l'étape n'a qu'un résultat, on considère que c'est le résultat de session 1. Si l'étape possède un 2em résultat on considère qu'il s'agit du résultat de session 2.
On procède ainsi pour ne pas avoir à identifier la session sur son libellé (ou sur le fait que le libellé contienne "1" ou "2") , sachant qu'il existe aussi des sessions identifiée comme "session unique" pour les étapes.
Le problème est donc de nouveau lié aux extractions qui permettent un peu de faire se qu'on veut (faire sauter des niveaux dans l'arborescence ou, ici, des résultats).
Une solution dans l'immédiat est de récupérer le résultat en session 1 dans l'extraction.
Sachant que je ne vois pas d'autres solutions que celle expliquée ci-dessus qui teste la libellé de la session (car le code session n'est pas gardé dans l'entité Etape affichée par MDW).

**Comment by cdubois54** [comment]
Je vais regarder pour ajouter, si possible, le code de  la session dans l'objet Resultat afin de permettre d’identifier correctement la session.

**Comment by cdubois54** [comment]
Je viens de commiter une correction sur la branche master (classes: Resultat.java et ResultatController.java)
si vous voulez/pouvez valider.

**Comment by yoannlecuyer** [comment]
Peux-tu m'envoyer le war stp ?
En effet, il me bloque lors de la compilation sur la récupération de la dépendance du WS Apogee 520lba.

**Comment by cdubois54** [comment]
Un mail avec un lien de téléchargement du war a dû partir automatiquement.

**Comment by cdubois54** [comment]
Attention, il y a 2 nouveaux paramètres de context permettant d'indiquer de
manière facultative un utilisateur des WebServices Apogée lors des
appels au WebService Apogée :
-apoWsUsername
-apoWsPassword

**Comment by yoannlecuyer** [comment]
Merci pour ta réactivité.
Et j'avais vu pour le nouveau paramètre en comparant avec mes configs versionnées.
Par contre, je viens de tester et du coup, il m'affiche la session 1 mais rien de la session 2.

**Comment by cdubois54** [comment]
Je ne comprends pas, je croyais qu'il n'y avait aucun résultat remonté pour la session 1?
Quelles sont les codes sessions concernées par les résultats de l'étape à afficher ?

**Comment by yoannlecuyer** [comment]
Je viens de retester pour te donner des exemples plus complet et finalement la Session 2 apparait correctement.
Je te redis lundi si le problème revient
