### ISSUE TITLE
Gestion des droits d'accès

### ISSUE THREAD

**Issue by gmartel** [EsupPortail/esup-mdw#20]
Bonjour,

Nous souhaitons disposer d'une gestion plus fine des droits d'accès dans MDW.
Nous aimerions en particulier :
- distinguer les profils enseignant, administratif (gestionnaire scolarité ou secrétaire pédagogique) et administrateur et pouvoir définir pour chacun les informations auxquelles il peut accéder
- ne limiter l'affichage des étudiants qu'à la composante à laquelle l'utilisateur appartient (sauf administrateur)

Merci d'avance.

**Comment by cdubois54** [comment]
Bonjour,

malheureusement une telle fonctionnalité, assez lourde à mettre en œuvre, avait été écartée à l'origine de la phase de développement de l'application.

Cordialement
