### ISSUE TITLE
Refonte de la récupération des notes depuis la maquette (Apogee-extraction)

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#22]
Bonjour,

Avec la nouvelle version d'Apogée 5.40.00 livrée ce matin, la demande que je leur avais remonté (139586) pour améliorer la méthode recupererMaquetteReleveResultat a été prise en compte et livrée dans cette version.

Pour info, en cas de récupération de note depuis une maquette (Apogee-extraction), l'AMUE préconise d'utiliser la méthode recupererMaquetteReleveResultat et pas recupererContratPedagogiqueResultatVdiVet.
En effet, la méthode recupererMaquetteReleveResultat permet de récupérer en plus les niveaux de décalage et le rang de chaque élément du relevé ce que ne permet pas l'autre méthode

Coté MDW, lorsqu'on paramètre avec Apogee-extraction, il faudrait donc que ce soit la méthode recupererMaquetteReleveResultat qui soit utilisée pour permettre d'organiser à l'identique de la maquette le rendu des relevés.

Merci d'avance.

Yoann Lecuyer

**Comment by cdubois54** [comment]
Bonjour,

nous comptons livrer une nouvelle version de MonDossierWeb d'ici 2 semaines contenant des modifications plutôt importantes, à savoir :
-Compatibilité openJDK11
-Utilisation d'une librairie cliente des WebServices Apogée générée en interne à la place de la librairie livrée par l'AMUE.
Cette version est d'ores et déjà en validation "à grande échelle" sur notre environnement de production.

Concernant la modification de monDossierWeb pour utiliser la nouvelle méthode recupererMaquetteReleveResultat cela ne peut actuellement pas être réalisé de notre côté par manque de disponibilité.
De plus notre environnement Apogée n'est pas paramétré pour utiliser les maquettes et nous ne pouvons donc pas tester de telles modifications sans impacter nos fonctionnels.

Cependant, depuis la version 1.2.3, le paramètre de contexte "resultat.implementation" permet de surcharger le comportement lors de la récupération des notes et résultats en développant sa propre classe java.
Cela avait été implémenté pour répondre aux soucis de l'Université Aix-Marseille qui avait des problèmes identiques avec les extractions.
Une personnalisation (voir une éventuelle contribution) est donc possible en étendant ResultatController et en le surchargeant avec l'utilisation de la méthode recupererMaquetteReleveResultat.

A noter que, dans cette optique, il serait sûrement plus interessant d'attendre la nouvelle version de monDossierWeb pour ne pas avoir à retroucher le code une seconde fois.

Charlie
