### ISSUE TITLE
Affichage du numéro d'anonymat

### ISSUE THREAD

**Issue by gmartel** [EsupPortail/esup-mdw#25]
Bonjour,

Dans l'onglet "Informations annuelles" de MDW, les étudiants peuvent voir leur(s) numéro(s) d'anonymat.
Mais dans de nombreux cas, les étudiants ne doivent pas en avoir connaissance avant la tenue des jurys car sinon, ils peuvent aller voir l'enseignant pour lui communiquer son numéro au moment de la correction.
Nous avons beaucoup d'étudiants qui ont un lien de parenté avec des enseignants.
Par ailleurs les gestionnaires Apogée ne donnent pas le numéro d'anonymat à l'étudiant mais les communiquent uniquement aux enseignants après la tenue des jurys pour la consultation des copies.

Est-il possible de rendre l'affichage de cette information facultatif ?

Merci.
Guillaume

**Comment by cdubois54** [comment]
Bonjour,

oui, nous ajouterons un paramètre pour désactiver l'affichage des numéros d'anonymat dans la prochaine version.

Cordialement

Charlie Dubois

**Comment by cdubois54** [comment]
v1.5.6
