### ISSUE TITLE
Problème de listing des inscrits à un ELP

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-mdw#27]
Bonjour,
Nous rencontrons un soucis d'affichage des inscrits à un ELP du fait de leur double inscription.
En effet, nous avons des étudiants qui sont inscrits à 2 étapes et ces 2 étapes ayant des éléments pédagogiques en commun, ces étudiants sont inscrits 2 fois à l'élément pédagogique au titre des 2 étapes.
Problème lors de la récupération des inscrits, cela crée une incohérence au niveau de l'affichage :
- sur l'écran de listing, l'étudiant n'apparait qu'une fois avec une étape choisie visiblement sur le critère d'inscription première dans Apogée
- dans l'export excel, l'étudiant apparait 2 fois mais avec à chaque fois l'étape d'inscription première

La solution serait d'avoir : 
- soit une seule ligne sans notion d'étape
- soit 2 lignes (ou plus) avec les différentes étapes

Par ailleurs, pour plus de clarté dans le code et la flexibilité du paramétrage, il serait pratique que les requêtes présentes dans différentes classes java (méthode ElementPedagogiqueServiceImpl.getInscritsFromElp par ex) soient toutes mises dans le fichier apogeeRequest.xml.

Cordialement,

Yoann Lecuyer (UR1)

**Comment by cdubois54** [comment]
Bonjour,

je reproduis bien le problème. Merci de l'avoir remonté.

Après réflexion, je pencherais plutôt pour la 2em solution.
Et voir, si possible, pour masquer une des 2 lignes si on décoche "Etape" (pour masquer la colonne).
Puis que l'export corresponde exactement à ce qui est affiché au moment où l'on clique sur le bouton d'export.

Concernant les requêtes présentes dans apogeeRequest.xml, j'essaye d'en ajouter à la demande.
Je vais essayer de voir combien il en reste pour estimer le temps que cela prendrait d'exporter les requêtes restantes. Je ne peux rien garantir.

Charlie

**Comment by yoannlecuyer** [comment]
Bonjour Charlie,
Effectivement, la seconde solution parait la plus pertinente si on veut garder la notion d'étape et le fait de pouvoir cacher la colonne serait aussi un plus.
Je prends note pour les requêtes. En espérant que tu puisses y parvenir.
Cordialement,
Yoann

**Comment by cdubois54** [comment]
Bonjour,

la version [1.5.6](https://github.com/EsupPortail/esup-mdw/releases/tag/1.5.6) corrige le bug.
Encore merci pour avoir remonté ce bug

Bonne fin de journée

Charlie
