### ISSUE TITLE
Affichage maquette semestre (Apogee-extraction)

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-mdw#3]
Bonjour,

Je transfère une demande que j'ai effectué sur la liste Esup/Sourcesup il y a quelques jours : 

https://listes.esup-portail.org/sympa/arc/esup-utilisateurs/2017-03/msg00013.html
et
https://sourcesup.renater.fr/tracker/index.php?func=detail&aid=11080&group_id=200&atid=886

Merci d'avance.

Cdt.

**Comment by cdubois54** [comment]
Le soucis vient-il uniquement de la pop-up du détail des notes ou il a déjà des anomalies sur la vue des notes et résultats en amont ?
En effet, sur les screenshots on voit 2 détails de notes portant sur 2 étapes différentes.

**Comment by devwald** [comment]
Bonjour,

sur les 2 (car en amont il n'y a d'affichage du résultat devant l'étape qui pose pb : vide)

Cdt.

**Comment by devwald** [comment]
A noter qu'un des 2 pb sera résolu par l'AMUE (demande d'assistance n°119912) : 

_"Bonjour,
Nous vous informons du changement de version de correction de votre fiche.
La correction devrait être prise en compte dans la version cible: 4.90.30
Cordialement,
Service maintenance APOGEE
Agence de mutualisation des universités et établissements"_

Il ne reste donc que mon PB d'affichage de la maquette semestre.

Cordialement.

**Comment by cdubois54** [comment]
Pour la vue en amont "notes et résultats" : on récupère les résultats de l'extraction pour l'année en cours + les résultats dans apogée pour les autres années.

Pour le "détail des notes", si on est paramétré en extraction-apogee, on regarde si l'année est candidate à l'extraction Apogée en fonction du paramètre applicatif "notesNombreAnneesExtractionApogee". 
Si l'année des notes demandées >= ( annéeEncours - notesNombreAnneesExtractionApogee -1 )
alors on va chercher dans l'extraction Apogée, sinon simplement dans Apogée.

Du coup, je me rends compte que la vue en amont "notes et résultats" devrait probablement intégrer la même règle...

Cela peut il expliquer votre problème?

**Comment by devwald** [comment]
Je ne pense pas.
Dans ma base j'ai notesNombreAnneesExtractionApogee à 100

Pour rappel, on se concentre sur l'étape de la 1ère année du Master intervention sociale.

Avec l'ancienne version qui correspond au canal uPortal (cf. https://sourcesup.renater.fr/frs/?group_id=200&release_id=606) : https://sourcesup.renater.fr/tracker/download.php/200/886/11080/1573/Ancienne-version.png (seule les lignes possédant une note s’affiche)
Avec la nouvelle version : https://sourcesup.renater.fr/tracker/download.php/200/886/11080/1574/Nouvelle-version.pdf (toutes les lignes s'affichent même celles qui n'ont pas de notes)

**Comment by cdubois54** [comment]
L'existence d'une note est une condition dans l'affichage d'une épreuve (en italique) mais pas d'un ELP.
