### ISSUE TITLE
Signature pour la quittance

### ISSUE THREAD

**Issue by benoit-tayrac** [EsupPortail/esup-mdw#35]
Bonjour,
Serait-il possible d'afficher la signature sur la quittance, comme cela est fait pour le certificat ?
Dans notre cas, nous utiliserions la même signature Apogée pour les deux documents. Donc les deux options suivantes pourrait être communes aux deux documents : certScolCodeSignataire & certScolDescSignataire.
Merci d'avance.
Benoit Tayrac
Université Toulouse 3

**Comment by cdubois54** [comment]
Bonjour, 

nous notons cette demande pour une prochaine version.
Probablement que cela donnera lieu à des nouveaux paramètres spécifiques à la quittance.

Cordialement

Charlie Dubois

**Comment by benoit-tayrac** [comment]
Bonjour,
Très bien. Merci.
Benoit Tayrac

**Comment by cdubois54** [comment]
Evolution disponible dans le release 1.6.3
https://www.esup-portail.org/wiki/x/K4BNHg
