### ISSUE TITLE
Affichage des boutons de téléchargement

### ISSUE THREAD

**Issue by benoit-tayrac** [EsupPortail/esup-mdw#36]
Bonjour, 
Nous utilisons l'affichage des boutons de téléchargement sur une nouvelle ligne.
Cependant, nous constatons un problème de marge pour les années antérieures à l'année en cours : Le bouton chevauche le libellé du dessus. 
![image](https://user-images.githubusercontent.com/86612234/123663427-ad2a5b80-d836-11eb-89c4-a56a1fc1be37.png)

De plus, en mode bouton, le fait d'avoir une couleur spécifique pour chaque élément ne parait plus nécessaire. Serait-il possible de rendre les couleurs optionnelles ? 

Merci d'avance.
Benoit Tayrac
Université Toulouse 3

**Comment by cdubois54** [comment]
Bonjour, 

Le soucis de chevauchement sera corrigé dans la prochaine version.

Concernant le fait de rendre les couleurs optionnelles, nous notons cette demande pour une réalisation ultérieure.

Cordialement

Charlie Dubois

**Comment by benoit-tayrac** [comment]
Bonjour,
Très bien. Merci.
Benoit Tayrac

**Comment by cdubois54** [comment]
Évolution disponible dans le release 1.6.2
https://www.esup-portail.org/wiki/x/K4BNHg
