### ISSUE TITLE
Critères d'affichage des cursus externes

### ISSUE THREAD

**Issue by benoit-tayrac** [EsupPortail/esup-mdw#37]
Bonjour,
Les critères pour afficher l'état AJOURNE se sont pas les mêmes dans notre cas.
En effet, un étudiant pour avoir temObtentionDip = N, alors qu'il n'a pas été ajourné.
Exemple : Si un étudiant a obtenu seulement une année (L1 par exemple), il aura  temObtentionDip = N et temObtentionNiveau = O
Voici ce que pourrait donner le code de la méthode  recupererInscriptions() de EtudiantController.java pour coller à notre cas : 

```
if ( (cext.getTemObtentionDip() != null && cext.getTemObtentionDip().equals("N")) &&
     (cext.getTemObtentionNiveau() != null && cext.getTemObtentionNiveau().equals("N")) ) {
	insc.setRes("AJOURNE");
} else {
	insc.setRes("OBTENU");
}
```
De plus, le traitement par défaut affiche un cursus externe seulement s'il y a un établissement, et si on a soit un typeAutreDiplome, soit un typeDiplomeExt.
Dans notre cas, l'établissement n'est pas toujours renseigné... 
La aussi, voici ce que pourrait donner le code de la méthode  recupererInscriptions() de EtudiantController.java pour coller à notre cas : 
```
if (cext.getEtablissement() != null || cext.getTypeDiplomeExt() != null || cext.getTypeAutreDiplome() != null) {
	if (cext.getEtablissement()!=null) {
		insc.setLib_etb(cext.getEtablissement().getLibEtb());
	}
...
```
Les bouts de code proposés ne sont la que pour traduire notre besoin, mais je me doute qu'ils ne correspondront surement pas au cas général.

Merci d'avance.
Benoit Tayrac
Université Toulouse 3

**Comment by cdubois54** [comment]
Bonjour,

concernant le diplôme, cela reviendrait à indiquer OBTENU si temObtentionDip = N et temObtentionNiveau = O.
Or le diplôme n'a, en réalité, pas été obtenu (à priori).
Nous allons rendre ces libellés paramétrables via le fichier messages.properties et en prévoir un troisième pour le cas où temObtentionDip = N et temObtentionNiveau = O.

Concernant le libellé de l'établissement, pas de soucis pour la prise en compte.

Ces modifications seront intégrées le plus rapidement possible

Cordialement

Charlie Dubois

**Comment by benoit-tayrac** [comment]
Bonjour,
Cela me parait parfait.
Merci beaucoup.
Benoit Tayrac

**Comment by cdubois54** [comment]
Évolution disponible dans le release 1.6.2
https://www.esup-portail.org/wiki/x/K4BNHg
