### ISSUE TITLE
Affichage calendrier épreuves différent desktop/mobile

### ISSUE THREAD

**Issue by HeleneDer** [EsupPortail/esup-mdw#43]
Bonjour,

On nous a signalé un affichage différent du calendrier des épreuves en desktop et en mobile.
En effet, le champs remonté pour la salle n'est pas le même.

Pour la version mobile nous avons  le _libellé long_  et pour la version desktop nous avons le _code_ de la salle.

Dans notre cas le code de la salle est plus parlant, du coup les étudiants qui consultent le calendrier sur leur mobile n'ont pas le même degré d'information.

Serait-il possible d'avoir une uniformité d'affichage entre les versions desktop et mobile, en ayant le libelle long **+** le code de la salle ?

Merci pour votre retour.
Hélène Dermian
Université Toulouse 3

**Comment by cdubois54** [comment]
Bonjour, 

dans la prochaine version si le libellé de la salle est valué, mdw affichera : codeSalle (libelléSalle) 
Sinon : codeSalle. 

J'en profite pour préciser qu'en Desktop, le libellé s'affiche en passant la soucis sur le code de la salle. 

Cordialement 

---------------------------------------- 
Charlie Dubois 
Direction du Numérique - SIED 
Université de Lorraine 
24-30 rue Lionnois 54000 NANCY

**Comment by HeleneDer** [comment]
Bonjour Charlie,

J'attendais d'installer la version pour vous répondre.
C'est chose faite. Tout me semble correspondre à ce que les étudiants souhaitaient.
Merci

Cordialement
