### ISSUE TITLE
Authentification CAS proxifiée

### ISSUE THREAD

**Issue by Glef** [EsupPortail/esup-mdw#5]
Bonjour,

Je souhaite utiliser des tickets de proxy CAS pour m'authentifier, existe-t-il une méthode ou des paramètres pour ça ?

J'ai essayé de chercher dans le code source de MonDossierWeb, mais il semblerait que dans votre implémentation actuelle de l'authentification CAS, il n'est pas possible de configurer quoi que ce soit d'autre que l'url du CAS. Je souhaite passer par une authentification proxifiée, en utilisant le org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter avec quelques paramètres, mais on dirait que ce n'est pas possible car la classe fr.univlorraine.mondossierweb.config.SecurityConfig force l'utilisation de Cas20ServiceTicketValidator. 
Est-il envisageable de rendre ça configurable, pour permettre d'utiliser CAS dans d'autres configuration que celle d'une authentification directe ?

**Comment by cdubois54** [comment]
Bonjour,

Effectivement ce type d'implémentation n'est pas possible actuellement.
S'il suffit, comme je l'imagine, de modifier l'appel à setTicketValidator() dans la méthode casAuthenticationProvider de la classe SecurityConfig.java , cela pourra être envisagé pour une future version.
Avez-vous, par hasard, un exemple de l'implémentation de cette méthode correspondant à votre besoin?

**Comment by prigaux** [comment]
@Glef ça m'intéresse de comprendre le cas d'utilisation d'un proxy ticket CAS pour mdw, pourrais tu détailler ? Merci !

**Comment by Glef** [comment]
@prigaux Mon cas d'utilisation consiste à afficher sur un ENT les informations de MonDossierWeb, sans avoir recourt à un iframe. L'ENT servirait donc de proxy pour faire transiter les tickets d'authentification CAS vers MonDossierWeb.
Dans le cas où CAS est configuré via le fichier web.xml, la technique standard pour permettre d'accepter un proxy de tickets consiste à ajouter le filtre suivant : https://wiki.jasig.org/display/casc/configuring+the+jasig+cas+client+for+java+in+the+web.xml#ConfiguringtheJasigCASClientforJavaintheweb.xml-org.jasig.cas.client.validation.Cas20ProxyReceivingTicketValidationFilter
Mais il me semble que ça ne soit pas possible dans l'implémentation actuelle de MonDossierWeb.

**Comment by prigaux** [comment]
@Glef, quel proxy ? WebProxyPortlet ? ou ?
Je m'interroge sur la possibilité d'arriver à proxifier du vaadin (en dehors du pb de l'authenfication).

PS : la solution alternative que nous utiliserons pour mettre esup-mdw dans notre ENT : https://www.esup-portail.org/wiki/display/pENT/ProlongationENT
