### ISSUE TITLE
Afficher notes et résultats seulement sur Epreuves et pas sur ELP

### ISSUE THREAD

**Issue by Nathalie-DLDB** [EsupPortail/esup-mdw#53]
Bonjour,

Est-il possible d'afficher dans MDW seulement les notes et résultats des épreuves d'un élément pédagogique sans extraire les notes et résultats de l'élément pédagogique ?

Cordialement,
Nathalie de Beaurecueil
Université Toulouse III - Paul Sabatier

**Comment by cdubois54** [comment]
Bonjour,

Pour que l'élément pédagogique soit masqué il faut que son état de délibération ne fasse pas partie des témoins de délibération permettant l'affichage.

Cela ne bloque pas l'affichage des épreuves sous l'élément si l'une des conditions suivante est respectée : 
- l'état de délibération de l'épreuve fait partie des témoin de délibération permettant l'affichage.
- le type de l'épreuve fait partie des types à afficher (paramètre applicatif "typesEpreuveAffichageNote")
- le témoin TemCtlValCadEpr de l'épreuve est égal au paramètre applicatif "temoinCtlValCadEpr" 

Cordialement

--
Charlie Dubois
Université de Lorraine

**Comment by Nathalie-DLDB** [comment]
Bonjour,

A UT3, sourceResultats est égal à "Apogee-extraction".
Les indications données dans votre réponse semblent correspondre à sourceResultats égal à "Apogee".

Les notes sur les épreuves s'affichent pour une session 1.
Nous n'arrivons pas à afficher les épreuves sur l'année en cours, dans le cas de session unique (codSes=0), que l'élément pédagogique soit affiché (complément de relevé dans la maquette avec "Note sur 20" et "Résultat" cochés) ou non affiché.
En mettant sourceResultat à "Apogee", les épreuves avec leurs notes ne sont pas non plus affichées pour une session unique.

Merci d'avance pour votre aide.
Cordialement,
Nathalie de Beaurecueil

**Comment by Nathalie-DLDB** [comment]
Bonjour,

Les épreuves avec leurs notes ne s'affichent pas pour tous les étudiants en session unique (licences FLEX, BUT...).
Pouvez-vous nous indiquer si un paramétrage dans MDW permet de résoudre ce problème ou si une évolution du web service _PedagogiqueMetierServiceInterface_ méthode _recupererContratPedagogiqueResultatElpEpr_v6_ doit être demandée à l'AMUE (les épreuves et leurs notes sont absentes du résultat retourné par le WS dans le cas d'une session unique).

Merci.
Cordialement,
Nathalie de Beaurecueil

**Comment by cdubois54** [comment]
Bonjour,

Concernant ce dernier message, la source de données de l'application est paramétrée en "Apogée" ou "Apogée-extraction" ?
En utilisant les extractions, MonDossierWeb ne pas filtre pas le retour du WebService sur le témoin de délibération.

Cordialement

--
Charlie Dubois
Université de Lorraine

**Comment by Nathalie-DLDB** [comment]
Bonjour,

La source de données de l'application est paramétrée en "Apogée-extraction".
MondossierWeb récupère les résultats du WS (et ne filtre pas le retour du WebService sur le témoin de délibération). 
C'est le WS recupererContratPedagogiqueResultatElpEpr_v6 qui ne retourne pas les épreuves et leurs notes dans le cas d'une session unique.
La DA 177254 est en cours avec l'AMUE pour faire évoluer le WS.

Merci pour vos réponses.
Cordialement,
Nathalie de Beaurecueil

**Comment by cdubois54** [comment]
Bonjour,

De rien.
Merci pour l'information. Nous n'étions pas du tout au courant de ce bug bloquant.

Bonne journée

--
Charlie Dubois
Université de Lorraine
