### ISSUE TITLE
Anomalie d'affichage du contrat pédagogique avec l'option Apogee-extraction

### ISSUE THREAD

**Issue by gmartel** [EsupPortail/esup-mdw#7]
Bonjour,

Nous utilisons la fonctionnalité Apogee-extraction pour l'affichage des notes dans mondossierweb.
Nous avons remarqué que la récupération du contrat pédagogique se faisait également avec cette option. En fait, en parcourant rapidement le code, il me semble que ce sont les mêmes objets qui sont utilisés dans les 2 vues.

Or le plus souvent, les maquettes de relevés de notes utilisées dans les extractions n'incluent pas l'ensemble des éléments pédagogiques du contrat de l'étudiant.
Il en résulte que le contrat pédagogique affiché n'est pas correct car il n'affiche que les éléments pédagogiques présents dans les maquettes d'extractions alors qu'il devrait afficher tous les éléments pour lesquels il y a une IP.

Serait-il possible de dissocier le contrat pédagogique pour l'affichage pédagogique de celui utilisé pour l'affichage des notes ?

Merci d'avance.
Cdlt

**Comment by cdubois54** [comment]
Bonjour,

effectivement, je comprends votre soucis, qui ne nous avait jamais été remonté jusque là.
N'utilisant pas, nous même, les extractions Apogée, nous n'avons pas rencontré ce soucis.

J'ajoute ce point dans les anomalies à traiter.
Malheureusement je ne peux m'engager sur un délai de réalisation.

Cordialement

**Comment by gmartel** [comment]
Bonjour Charlie,

As-tu une idée plus précise de délai pour le traitement de cette anomalie ?

Cordialement

**Comment by cdubois54** [comment]
Bonjour,

je pensais pouvoir faire cela courant mars mais je n'ai pas eu la disponibilité espérée.
La prochaine version contiendra la correction de ce problème mais également d'autres évolutions/corrections.  J'essaye de regrouper les livraisons au maximum pour en faire le moins possible.
Je ne sais pas si j'aurais le temps la semaine prochaine, mais ça devrait être fait courant avril.

Cordialement

**Comment by cdubois54** [comment]
Normalement le problème est résolu dans la dernière version.
Merci de me confirmer cela. Je fermerais alors ce ticket.
