### ISSUE TITLE
note min - max

### ISSUE THREAD

**Issue by sumoo13** [EsupPortail/esup-mdw#8]
bonjour,

nous avons déjà accès a une instance de mondossierweb via notre ENT hébergée par notre COMUE NU
nous n'avons donc pas la main dessus, on se pose des questions sur l’éventualité d'héberger une instance en local.
une des principales raisons, est que nous souhaiterions l'affichage des notes min et max par matière pour un étudiant, en plus de sa note.
est ce une option déjà implantée, sinon serait ce compliqué à ajouter ?

**Comment by cdubois54** [comment]
Bonjour,

cette option n'est pas implantée dans MDW.
Je n'ai pas bien compris s'il s'agissait d'afficher les notes min/max d'une promotion pour une VET sur la vue 'Notes et Résultats' à côté de la note de l'étudiant, ou à un élément sur la vue 'Détail des notes'.
Dans tous les cas, cela ne semble pas évidemment étant donné que l'information n'est, à ma connaissance, pas retournée par le WS Apogée (il faut également savoir où/comment afficher l'information).

Cordialement
