### ISSUE TITLE
Compatibilité Apogée Version 5.00.30 / Esup-MDW

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-mdw#9]
Bonjour,

La nouvelle version d'Apogée (5.00.30) nécessite une mise à jour des WebServices Apogée (avec la livraison d'un nouveau client : apo-webservicesclient500lba.jar).

Pouvez vous m'indiquer si la dernière version d'Esup-MDW (1.2.2) est bien compatible avec cette version d'Apogée ?

Si c'est le cas, peut-on mettre à jour le client .jar côté Esup-MDW ? (apo-webservicesclient500lba.jar)

Merci d'avance.

Cordialement.

**Comment by cdubois54** [comment]
Bonjour,

je n'ai pas encore pu tester mdw avec cette nouvelle librairie mais cela ne saurait tarder.

Cordialement

**Comment by cdubois54** [comment]
Rebonjour,

je viens de tester rapidement mdw avec le librairie cliente 500lba, cela ne semble pas poser de problème.

Cdlt
